name: Deploy AWS CDK

on:
  #push:
  #  branches: [main]
  #pull_request:
  #  branches: [main]
  workflow_dispatch:

env: 
    RUSTFLAGS: --cfg=web_sys_unstable_apis

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone Leptos Website Repository
        run: git clone https://github.com/Andrewp2/nexus.git
        working-directory: ${{ github.workspace }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Install npm
        run: 'sudo apt update -y && sudo apt install nodejs npm -y'
      
      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk'

      - name: Install Rust
        id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          targets: "wasm32-unknown-unknown"
          components: "rustfmt"

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-lambda
        run: cargo install cargo-lambda

      - name: Install cargo-leptos
        run: cargo install cargo-leptos
        
      - name: Build Leptos Website
        run: cargo leptos build --release
        working-directory: ${{ github.workspace }}/nexus

      - name: Build Proudction Server Binary
        run: LEPTOS_OUTPUT_NAME=aws-lambda cargo lambda build --no-default-features --features=ssr --release
        working-directory: ${{ github.workspace }}/nexus

      - name: CDK Synth
        run: cdk synth
        working-directory: CDK-AWS

      - name: CDK Deploy
        run: cdk deploy
        working-directory: CDK-AWS